# Generated by Django 3.1.5 on 2021-02-05 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0028_auto_20210205_1823'),
        ('accounts', '0002_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=1000)),
                ('avatarurl', models.CharField(blank=True, default='https://icon-library.com/images/unknown-person-icon/unknown-person-icon-17.jpg', max_length=1000)),
                ('avatar_img', models.ImageField(blank=True, upload_to='images')),
                ('tribes', models.ManyToManyField(blank=True, to='app.Tribe')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
