# Generated by Django 3.1.5 on 2021-01-24 11:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210123_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='tribe',
            name='url',
            field=models.CharField(default=django.utils.timezone.now, max_length=60, unique=True),
            preserve_default=False,
        ),
    ]
