# Generated by Django 3.1.5 on 2021-01-24 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tribe_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tribe',
            name='url',
        ),
    ]
