# Generated by Django 3.1.5 on 2021-01-24 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_tribe_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tribe',
            old_name='user',
            new_name='creator',
        ),
    ]
