# Generated by Django 3.1.5 on 2021-02-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210203_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='tribe',
            name='genre',
            field=models.CharField(default='Jazz', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tribe',
            name='logourl',
            field=models.CharField(default='https://static.hollywoodreporter.com/sites/default/files/2019/03/avatar-publicity_still-h_2019-compressed.jpg', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatarurl',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
