# Generated by Django 3.1.5 on 2021-02-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210203_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tribe',
            old_name='creator',
            new_name='chieftain',
        ),
        migrations.AddField(
            model_name='profile',
            name='tribes',
            field=models.ManyToManyField(to='app.Tribe'),
        ),
    ]
