# Generated by Django 3.1.5 on 2021-02-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210203_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tribes',
            field=models.ManyToManyField(blank=True, to='app.Tribe'),
        ),
    ]
