# Generated by Django 3.1.5 on 2021-02-04 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210203_1059'),
        ('app', '0015_playlist_description'),
    ]

    operations = [
    ]
