# Generated by Django 3.1.5 on 2021-02-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210204_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatarurl',
            field=models.CharField(default='https://icon-library.com/images/unknown-person-icon/unknown-person-icon-17.jpg', max_length=1000),
        ),
        migrations.AlterField(
            model_name='tribe',
            name='logourl',
            field=models.CharField(default='https://w7.pngwing.com/pngs/708/110/png-transparent-american-horse-native-americans-in-the-united-states-tribal-chief-others-logo-head-indigenous-peoples-of-the-americas.png', max_length=1000),
        ),
    ]
