# Generated by Django 3.1.5 on 2021-02-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210204_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='tribe',
            name='logourl',
            field=models.CharField(default='http://localhost:8000/static/app/chieftain-logo.png', max_length=1000),
        ),
    ]
