# Generated by Django 3.1.5 on 2021-02-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210204_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
