# Generated by Django 3.1.5 on 2021-02-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_profile_avatar_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
