# Generated by Django 3.1.5 on 2021-02-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20210205_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='tribe',
            name='logo_img',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
