# Generated by Django 3.1.5 on 2021-02-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_tribe_logo_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatarurl',
            field=models.CharField(blank=True, default='https://icon-library.com/images/unknown-person-icon/unknown-person-icon-17.jpg', max_length=1000),
        ),
        migrations.AlterField(
            model_name='tribe',
            name='logourl',
            field=models.CharField(blank=True, default='http://localhost:8000/static/app/chieftain-logo.png', max_length=1000),
        ),
    ]
