# Generated by Django 3.1.5 on 2021-02-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20210205_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribe',
            name='logo_img',
            field=models.ImageField(blank=True, upload_to='images/tribes'),
        ),
    ]
