# Generated by Django 3.1.5 on 2021-02-05 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile'),
        ('app', '0028_auto_20210205_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribe',
            name='chieftain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
