# Generated by Django 3.1.5 on 2021-02-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile'),
        ('app', '0033_auto_20210206_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='likes',
            field=models.ManyToManyField(related_name='song_like', to='accounts.Profile'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
