# Generated by Django 3.1.5 on 2021-02-18 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20210218_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='playlist',
        ),
        migrations.AddField(
            model_name='comment',
            name='song',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.song'),
            preserve_default=False,
        ),
    ]
