# Generated by Django 3.1.5 on 2021-02-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20210218_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='minutes',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='seconds',
            field=models.PositiveIntegerField(),
        ),
    ]
