# Generated by Django 3.1.5 on 2021-03-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20210219_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_duration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
