# Generated by Django 3.1.5 on 2021-03-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_song_song_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_duration',
            field=models.DateTimeField(null=True),
        ),
    ]
