# Generated by Django 3.1.5 on 2021-03-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_auto_20210303_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_duration',
            field=models.DateTimeField(blank=True),
        ),
    ]
