# Generated by Django 3.1.5 on 2021-03-03 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_auto_20210303_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='minutes',
        ),
        migrations.RemoveField(
            model_name='song',
            name='seconds',
        ),
    ]
