# Generated by Django 3.1.5 on 2021-03-03 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_auto_20210303_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_duration',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
